apiVersion: serving.knative.dev/v1beta1
kind: Service
metadata:
  name: express
spec:
  template:
    spec:
      containers:
        - image: quay.io/csantanapr/kubecon-express
          ports:
            - containerPort: 3000
          env:
            - name: TARGET
              value: "KubeCon"
          livenessProbe:
            failureThreshold: 12
            httpGet:
              path: /live
            initialDelaySeconds: 5
            periodSeconds: 2
          readinessProbe:
            failureThreshold: 12
            httpGet:
              path: /ready
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
